name: Executar Notebook no Colab

on:
  schedule:
    - cron: '0 12 * * *'  # 9h da manhã no Brasil (UTC+0 é 12h)
  workflow_dispatch:  # Permite execução manual

jobs:
  run-colab:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Instalar Jupyter
        run: pip install notebook

      - name: Executar Notebook
        run: jupyter nbconvert --execute --to notebook --inplace marchon_py.ipynb
